---
- block:
  - ansible.builtin.set_fact:
      download_and_link_files: "{{ download + link }}"

  - name: Create destination directories
    ansible.builtin.file:
      path: "{{ item.dest | dirname }}"
      state: directory
    loop: "{{ download_and_link_files }}"

  - name: Check existing files
    ansible.builtin.stat:
      path: "{{ item.dest }}"
    loop: "{{ download_and_link_files }}"
    register: stat_result

  - name: Backup existing files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ item }}.backup-{{ ansible_date_time.iso8601_basic_short }}"
    loop: "{{ stat_result.results | map(attribute='stat') | selectattr('exists') | map(attribute='path') | unique | list }}"

  - name: Download remote files
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
    loop: "{{ download }}"

  - name: Link local files
    ansible.builtin.file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop: "{{ link }}"
