---
- name: Packages marked for installation
  ansible.builtin.debug:
    var: packages

- name: Packages with classic confinement marked for installation
  ansible.builtin.debug:
    var: classic_packages

- name: Selected channel for the packages
  ansible.builtin.debug:
    var: channel

- import_role:
    name: install
  vars:
    system: [ snapd ]

- name: Symlink snap executable (RedHat-based only)
  when: ansible_facts["os_family"] == "RedHat"
  become: yes
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Install packages
  community.general.snap:
    classic: no
    state: present
    channel: "{{ channel }}"
    name: "{{ packages }}"

- name: Install packages requiring classic confinement
  community.general.snap:
    classic: yes
    state: present
    channel: "{{ channel }}"
    name: "{{ classic_packages }}"
