---
- block:
  - name: Check required variables exist and have values
    ansible.builtin.assert:
      that:
        - "{{ item }} is defined"
        - "{{ item }} != None"
        - "{{ item }} | length > 0"
      fail_msg: "Variable {{ item }} is required."
      success_msg: "Required variable {{ item }} is defined"
    loop:
      - user_name
      - user_email

  - name: Set global user.name
    ansible.builtin.command:
      argv:
        - git
        - config
        - --global
        - user.name
        - "{{ user_name }}"

  - name: Set global user.email
    ansible.builtin.command:
      argv:
        - git
        - config
        - --global
        - user.email
        - "{{ user_email }}"
  rescue:
    - ansible.builtin.debug:
        msg: |
          Ignored git config because of undefined variables.
          Check the messages above.
        verbosity: 0